logging:
  path: logs/healbro.log
  level:
    com.epam.learning.aykorenev: INFO
    org.springframework.web: DEBUG
liquibase:
  change-log: classpath:/db/changelog/db.changelog-master.yml
server:
  port: 9090
spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: false
---
spring:
  jpa:
    show-sql: true
  datasource:
      url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL
      username: sa
      password:
      driver-class-name: org.h2.Driver
      platform: h2
  profiles: dev
  template:
    cache: false
  h2:
    console:
      enabled: true
management:
  security:
    enabled: false
---
spring:
  profiles: prod
